language: node_js

node_js:
  - 10.2.1


addons:
  ssh_known_hosts: github.com

install:
  - npm install -g hexo
  - npm install



before_script:
  - openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - git config user.name fomav
  - git config user.email fomav@foxmail.com

script:
  - hexo d

