language: node_js

node_js:
  - 10.2.1



install:
  - npm install -g hexo
  - npm install



before_script:
  - git config user.name fomav
  - git config user.email fomav@foxmail.com

script:
  - hexo d

