language: node_js

node_js:
  - 10.2.1


branches:
  only:
    - master

addons:
  ssh_known_hosts:
    - github.com
    - blog.fomav.cn

cache:
  directories:
    - node_modules


before_install:
  - git config --global user.name fomav
  - git config --global user.email fomav@foxmail.com
  - openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
    -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - eval $(ssh-agent)
  - ssh-add id_rsa

install:
  - npm install -g hexo
  - npm install

before_script:
  - git clone git@github.com:fmwalways/Hexo_Blog_Static.git .deploy_git

script:
  - hexo d

deploy:
  provider: script
  script: bash deploy/deploy_aliyun.sh $SSH_USER $SSH_HOST $SSH_PORT
  on:
    branch: master


