language: node_js

node_js:
  - 10.2.1


addons:
  ssh_known_hosts: github.com



before_install:
  - git config --global user.name fomav
  - git config --global user.email fomav@foxmail.com

install:
  - npm install -g hexo
  - npm install



before_script:
  - openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
    -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - eval $(ssh-agent)
  - ssh-add id_rsa
  - git clone git@github.com:fmwalways/Hexo_Blog_Static.git .deploy_git

script:
  - hexo d




