git add .;
echo "";
echo "git添加完毕";
echo "";
git commit -m "blog update";
echo "";
echo "git提交更改完毕";
echo "";
git push tblog master;
git push tbblog master;
Git push gblog master;
echo "";
echo "推送成功";