name: Hexo_Blog_CI

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare hexo repository
        uses: actions/checkout@v3
      - name: prepare node environment
        uses: actions/setup-node@v3
        with:
          node-version: 10.2.1
      - name: prepare cache node_module
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}
      - name: prepare npm environment
        run: |
          npm install -g hexo
          npm install
      - name: deploy cloud server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          script: cd /home/blog/; git fetch --all && git reset --hard origin/master && git pull
