name: Hexo Blog CI

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm environment prepare
        uses: actions/setup-node@v3
        with:
          node-version: 10.2.1
      - run: npm install -g hexo
      - run: npm install
